(function(b){var a=window.AmazonUIPageJS||window.P,d=a._namespace||a.attributeErrors,c=d?d("ARARegisterTriggerSubAssets@utils",""):a;c.guardFatal?c.guardFatal(b)(c,window):c.execute(function(){b(c,window)})})(function(b,a,d){b.now("ARAConfiguration").execute(function(a){a||b.register("ARAConfiguration",function(){return{getRoboticSessionId:function(){return"000-0000000-0000000"},getUserAgent:function(){return navigator.userAgent}}})});"use strict";b.now("ARAAddMetric").execute(function(c){c||b.register("ARAAddMetric",
function(){return{addMetric:function(b,c){a.ue&&a.ue.count&&a.ue.count(b,c)}}})});"use strict";b.now("ARALogError").execute(function(c){c||b.register("ARALogError",function(){return{logError:function(b){var c={logLevel:2<arguments.length&&arguments[2]!==d?arguments[2]:"ERROR",attribution:"ARARegisterTrigger",message:1<arguments.length&&arguments[1]!==d?arguments[1]:""};a.ueLogError&&a.ueLogError(b,c);return[b,c]}}})});"use strict";b.now("ARAUtils").execute(function(c){c||b.when("ARAAddMetric").register("ARAUtils",
function(b){function c(){return a.ue_pty}var p=/development|beta/,f=/pre-prod|gamma/,q={"Google Chrome":106};return{getWindowOpts:function(){return a.opts},getHref:function(){return a.location.href},getStage:function(a){return p.test(a)?"beta":f.test(a)?"gamma":"prod"},getCustomerId:function(){var e=c()||"";if(a.fwcimData)return b.addMetric("ARA:UsingFWCIMDataCustomerId:"+e,1),a.fwcimData.customerId;if(a.opts)return b.addMetric("ARA:UsingWindowOptsCustomerId:"+e,1),a.opts.customerId;b.addMetric("ARA:FailedToGetCustomerId:"+
e,1)},getRequestId:function(){if(a.ue)return a.ue.rid},getASIN:function(){return a.ue_pti},getMarketId:function(){if(a.ue)return a.ue.mid},getSessionId:function(){if(a.ue)return a.ue.sid},getPageType:c,getPageLoadStartTime:function(c){if(a.ue&&a.ue.t0)return a.ue.t0;b.addMetric("ARA:FailedToGetPageLoadStart:"+c,1);return!1},getNavigator:function(){return navigator},registerFetch:function(b){return a.fetch(b,{keepalive:!0,attributionReporting:{eventSourceEligible:!1,triggerEligible:!0}})},checkIsBrowserSupported:function(){var a=
navigator.userAgentData;if(null==a)return!1;a=a.brands;a:{if(a&&0!==a.length){var b=!0,c=!1,l=d;try{for(var g=a[Symbol.iterator](),m;!(b=(m=g.next()).done);b=!0){var n=m.value;if(Number.parseFloat(n.version)>=q[n.brand]){var f=!0;break a}}}catch(r){c=!0,l=r}finally{try{!b&&g.return&&g.return()}finally{if(c)throw l;}}}f=!1}return f},checkIsFeatureAllowed:function(){return"featurePolicy"in document&&"function"===typeof document.featurePolicy.allowsFeature?document.featurePolicy.allowsFeature("attribution-reporting"):
!1},getDetailPageState:function(){if(a.DetailPage&&a.DetailPage.StateController)return a.DetailPage.StateController.getState()}}})});"use strict";b.now("ARARegisterTriggerHelpers").execute(function(a){a||b.when("ARAConfiguration","ARAAddMetric","ARALogError","ARAUtils").register("ARARegisterTriggerHelpers",function(a,b,c,f){function d(a){switch(a){case "beta":return"https://beta-ara.paa-reporting-advertising.amazon";case "gamma":return"https://gamma-ara.paa-reporting-advertising.amazon";case "prod":return"https://ara.paa-reporting-advertising.amazon"}}
function e(a){return d(a)+"/conversion?"}function h(a){var b=encodeURIComponent;return Object.keys(a).map(function(c){return Array.isArray(a[c])?a[c].map(function(a){return b(c)+"\x3d"+b(a)}).join("\x26"):b(c)+"\x3d"+b(a[c])}).join("\x26")}function k(a,g,d,e,h){return f.registerFetch(a).then(function(c){if(d<e)return c.ok?(b.addMetric("ARA:RegisterTriggerResponseReceived:"+g,1),c.json()):new Promise(function(b,c){setTimeout(function(){k(a,g,d+1,e,2*h).then(b).catch(c)},h)});throw Error("Exceeded maximum retries");
}).catch(function(a){b.addMetric("ARA:RegisterTriggerResponseError:"+g,1);c.logError(a,"ARA:RegisterTriggerResponseError:"+g+". Error receiving response from ARAService")})}return{generateGatewayUrl:d,browserSupportsARA:function(a){var c=f.checkIsBrowserSupported(),d=f.checkIsFeatureAllowed();c?d||b.addMetric("ARA:ARAFeatureNotEnabled:"+a,1):b.addMetric("ARA:UserAgentNotSupported:"+a,1);return c&&d},registerTrigger:k,generateQuery:h,generateConversionBaseUrl:e,generateUrl:function(a,b){return e(b)+
h(a)}}})})});
/* ******** */
(function(f){var g=window.AmazonUIPageJS||window.P,h=g._namespace||g.attributeErrors,b=h?h("ARARegisterTriggerSubAssets@search",""):g;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,g,h){f.now("ARASearch").execute(function(b){b||(f.when("A").register("ARASearch",function(b){var a={},c=b.$;a.init=function(k,m,e,d,b,c){a.config=k;a.helpers=d;a.utils=b;a.metrics=m;a.errors=e;a.swac=c;a.retrieveSearch()};a.retrieveAllAsins=function(){var a=[];c("[data-asin]").each(function(k,
e){c(e).data().asin&&a.push(c(e).data().asin)});return a};a.retrieveAllSponsoredAsins=function(){var a=[];c("[data-asin].AdHolder, .AdHolder [data-asin]").each(function(k,e){c(e).data().asin&&a.push(c(e).data().asin)});return a};a.getEligibleAsins=function(){var k=a.retrieveAllAsins(),b=a.retrieveAllSponsoredAsins();return k.filter(function(a){var d=b.findIndex(function(b){return b===a});return 0<=d?(b.splice(d,1),!1):!0})};a.retrieveSearch=function(){var b=a.utils.getHref();if(b)if(a.helpers.browserSupportsARA("SEARCH")){a.metrics.addMetric("ARA:BrowserSupportsARA:SEARCH",
1);var c=a.utils.getStage(b),e=a.utils.getSessionId(),d=a.utils.getCustomerId(),f=a.utils.getMarketId(),g=a.utils.getRequestId();b=a.utils.getPageType();var l=a.config.getRoboticSessionId();e=e===l;l=a.swac.getSearchMetadata().keywords;var h=a.getEligibleAsins();e?(a.metrics.addMetric("ARA:TotalPunts:SEARCH",1),a.metrics.addMetric("ARA:RoboticTraffic:SEARCH",1)):l&&0<l.length?(d={eventType:"searchConversion",debugKey:d,obfuscatedMarketplaceId:f,requestId:g,trackedItem:l,trackedItemType:"Keyword",
asins:h.slice(0,5)},d=a.helpers.generateUrl(d,c),c=Date.now(),a.helpers.registerTrigger(d,"SEARCH",0,1,100),(d=a.utils.getPageLoadStartTime(b))&&a.metrics.addMetric("ARA:ScriptLoadLatency:"+b,c-d)):a.metrics.addMetric("ARA:KeywordsNotFoundError:SEARCH",1)}else a.metrics.addMetric("ARA:BrowserDoesNotSupportARA:SEARCH",1);else a.metrics.addMetric("ARA:PageLoadError:SEARCH",1),a.errors.logError({message:"ARA:PageLoadError:SEARCH. Error retrieving url from window."})};return a}),f.when("ARAConfiguration",
"ARAAddMetric","ARALogError","ARARegisterTriggerHelpers","ARAUtils","ARASearch","s-web-application-controller","ready").execute(function(b,a,c,f,g,e,d){e.init(b,a,c,f,g,d)}))})});
/* ******** */
